### ISSUE TITLE
Prism version number incorrect in admin/package.json

### ISSUE THREAD

**Issue by mattsimpson** [Kwaai-AI-Lab/paios#1]
Upon attempting to get the Paios admin interface running for the first time I encountered the following error when running `npm install`.

```
~/S/p/admin (main)> npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for prism@^5.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR! 2024-04-24T00_27_32_589Z-debug-0.log
```

It turns out there isn't Prism version 5.7.0: https://www.npmjs.com/package/prism

After updating this to version 4.1.2, `npm install` and `npm run dev` ran correctly.

**Comment by iormungand** [comment]
From the instructions, it seems the prism intended is an API mocking package, https://github.com/stoplightio/prism, with latest version 5.7.0 matching the specified version. The correct name is probably "@stoplight/prism-cli".
This also correctly builds, but the instructions indicate a prism binary, which will only be present if the package is installed globally, or the node_modules/.bin directory is in the PATH. The instructions probably should be updated to reflect this.

**Comment by samj** [comment]
Thanks @mattsimpson for the fix (and @iormungand for confirming the cause).

No need for mocking now we have a working backend so I've pulled it out and closed the issue.
